---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: 5.5.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitlab/gitlab-ce
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: "gitlab.${SECRET_DOMAIN}"
          paths:
            - /
      tls:
        - hosts:
            - "gitlab.${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    edition: ce
    