apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - "gitlab-charts.yaml"
  - "bitnami-charts.yaml"
  - "metallb-charts.yaml"
  - "jetstack-charts.yaml"
  - "external-dns-charts.yaml"
  - "nginx-charts.yaml"
  - "longhorn-charts.yaml"
  - "grafana-charts.yaml"
  - "prometheus-community-charts.yaml"
