---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  values:
    interval: 5m
    logLevel: debug
    provider: pdns
    env:
      - PDNS_API_KEY: "${SECRET_PDNS_API_KEY}"
      - PDNS_API_URL: "${SECRET_PDNS_API_URL}"
    extraArgs:
      - --pdns-server=$(PDNS_API_URL)
      - --pdns-api-key=$(PDNS_API_KEY)
    policy: sync
    sources:
      - ingress
    txtPrefix: "k8s."
    txtOwnerId: "default"
    domainFilters:
      - "${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi