---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton 
  namespace: tekton 
spec:
  interval: 5m
  chart:
    spec:
      chart: cdf/tekton-pipeline 
      version: 0.27.2
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      git:
        username: "admin"
        password: ""
        url: https://github.com
      docker:
        configJson: ""
    serviceaccount:
      enabled: true
      annotations: {}
    controller:
      deployment:
        labels: {}
      pod:
        labels: {}
        annotations: {}
      envFromSecret: "tekton-env"
    webhook:
    deployment:
        labels: {}
      pod:
        labels: {}
      envFromSecret: "tekton-env"
    configDefaults: {}
    featureFlags: {}
